/**
 * Classify MCP tool calls as read vs write for approval gating.
 * Unknown action/* tools default to write (safe default).
 */

export type OpClass = 'read' | 'write';

const READ_TOOLS = new Set([
  'hcm_health',
  'hcm_whoami',
  'hcm_list_resources',
  'hcm_describe_resource',
  'hcm_search_workers',
  'hcm_get_worker',
  'hcm_get_worker_assignments',
  'hcm_search_absences',
  'hcm_get_absence',
  'hcm_absence_balance',
  'hcm_get_plan_balance',
  'hcm_search_aor',
  'hcm_get_aor',
  'hcm_list_checklists',
  'hcm_get_checklist',
  'hcm_list_notifications',
  'hcm_get_notification',
  'hcm_search_organizations',
  'hcm_get_organization',
  'hcm_search_locations',
  'hcm_get_location',
  'hcm_search_jobs',
  'hcm_get_job',
  'hcm_search_grades',
  'hcm_get_grade',
  'hcm_search_time_records',
  'hcm_get_time_record',
  'hcm_search_talent_profiles',
  'hcm_get_talent_profile',
  'hcm_search_payroll_relationships',
  'hcm_get_payroll_relationship',
  'hcm_rest_get',
  'hcm_list_pending_approvals',
  'hcm_list_atom_entries',
  'hcm_detect_changes',
  'hcm_search_requisitions',
  'hcm_get_requisition',
  'hcm_search_candidates',
  'hcm_get_candidate',
  'hcm_search_benefit_enrollments',
  'hcm_get_benefit_enrollment',
  'hcm_lov_finder',
  'hcm_resolve_uniq_key',
  'hcm_setup_status',
  'hcm_test_connection',
  'hcm_emit_mcp_config',
  'hcm_search_public_workers',
  'hcm_get_public_worker',
  'hcm_search_contacts',
  'hcm_get_contact',
  'hcm_search_phones',
  'hcm_search_emails',
  'hcm_search_national_identifiers',
  'hcm_get_national_identifier',
  'hcm_get_work_relationship',
  'hcm_search_positions',
  'hcm_get_position',
  'hcm_list_direct_reports',
  'hcm_get_org_hierarchy',
  'hcm_find_locations',
  'hcm_search_absence_types',
  'hcm_search_absence_plans',
  'hcm_get_absence_type_balance',
  'hcm_search_schedules',
  'hcm_get_schedule',
  'hcm_search_goals',
  'hcm_get_goal',
  'hcm_search_performance_documents',
  'hcm_get_performance_document',
  'hcm_search_learning_enrollments',
  'hcm_get_learning_enrollment',
  'hcm_search_compensation',
  'hcm_get_compensation',
  'hcm_search_bank_accounts',
  'hcm_get_bank_account',
  'hcm_search_payment_methods',
  'hcm_search_element_entries',
  'hcm_search_calculation_cards',
  'hcm_search_payslips',
  'hcm_get_payslip',
  'hcm_list_audit_trail',
  'hcm_bulk_bp_dry_run',
  'hcm_explain_tool',
  'hcm_dry_run_mutate',
  'hcm_probe_capabilities',
  'hcm_rbac_hint',
  'hcm_list_webhook_events',
    'hcm_export_config',
  'hcm_list_atom_feeds',
  'hcm_get_atom_feed',
  'hcm_get_atom_entry',
  'hcm_atom_poll',
  'hcm_atom_consume',
  'hcm_atom_get_checkpoint',
  'hcm_atom_reset_checkpoint',
  'hcm_lov_find',
  'hcm_describe_finder',
  'hcm_smoke_probe',
  'hcm_list_smoke_reports',
  'hcm_list_profiles',
  'hcm_emit_profile_mcp_config',
  'hcm_oauth_token_status',
  'hcm_test_as_user',
  'hcm_get_legislative_data',
  'hcm_list_work_relationships',
  'hcm_get_assignment_history',
  'hcm_person_deep_read',
  'hcm_search_offers',
  'hcm_get_offer',
  'hcm_search_interviews',
  'hcm_get_interview',
  'hcm_list_candidate_attachments',
  'hcm_validate_time_card',
  'hcm_get_time_card',
  'hcm_list_redaction_audit',
  'hcm_atom_replay',
  'hcm_atom_real_pod_guide',
  'hcm_batch_get',
  'hcm_get_absence_type',
  'hcm_get_absence_plan',
  'hcm_balance_by_plan',
  'hcm_bulk_bp_preview',
]);


const WRITE_TOOLS = new Set([
  'hcm_create_worker',
  'hcm_update_worker',
  'hcm_create_absence',
  'hcm_update_absence',
  'hcm_delete_absence',
  'hcm_create_aor',
  'hcm_update_aor',
  'hcm_delete_aor',
  'hcm_update_task_status',
  'hcm_perform_bp_action',
  'hcm_update_talent_profile',
  'hcm_rest_mutate',
  'hcm_approve_write',
  'hcm_deny_write',
  'hcm_allocate_checklist',
  'hcm_force_close_checklist',
  'hcm_create_worker_assignment',
  'hcm_update_worker_assignment',
  'hcm_submit_time_card',
  'hcm_bulk_approve_notifications',
  'hcm_bulk_deny_notifications',
  'hcm_start_webhook_receiver',
  'hcm_switch_profile',
  'hcm_upsert_profile',
  'hcm_oauth_refresh',
  'hcm_enroll_benefit',
  'hcm_opt_out_benefit',
  'hcm_recipe_new_hire_checklist',
  'hcm_recipe_absence_balance_approve',
  'hcm_recipe_time_submit',
  'hcm_clear_redaction_audit',
  'hcm_webhook_rotate_secret',
  'hcm_create_goal',
  'hcm_update_goal',
  'hcm_enroll_learning',
  'hcm_update_learning_enrollment',
  'hcm_update_compensation',
]);

export function classifyTool(name: string): OpClass {
  if (READ_TOOLS.has(name)) return 'read';
  if (WRITE_TOOLS.has(name)) return 'write';
  if (name.startsWith('hcm_') && /create|update|delete|mutate|perform|patch|post|put|submit|allocate|force|approve|deny/i.test(name)) {
    return 'write';
  }
  if (name.startsWith('hcm_')) return 'write';
  return 'write';
}

export function isReadTool(name: string): boolean {
  return classifyTool(name) === 'read';
}

export function isWriteTool(name: string): boolean {
  return classifyTool(name) === 'write';
}

export { READ_TOOLS, WRITE_TOOLS };
